-- REPARARE DEFINITIVA BAZA DE DATE RedM (VORP)
-- Acest script adauga toate itemele lipsa si corecteaza casing-ul (toate literele mici)

-- Pas 1: Ne asiguram ca itemele de baza sunt usable (folosibile)
UPDATE `items` SET `usable` = 1 WHERE `item` IN (
    'horsemeal', 'stim', 'unique_brad_horsesugar', 'unique_horse_feed', 
    'portable_canoe', 'idcard', 'broom', 'goldpan', 'handcuffs', 'antipoison', 
    'unique_ayahuasca_diablo', 'vodka', 'beer', 'tequila', 'hemp', 'heroin', 
    'cookedbluegil', 'cheesecake', 'chococake', 'syringe', 'p_crawdad01x', 
    'p_finishedragonfly01x', 'p_finishdcrawd01x', 'p_finishedragonflylegendary01x', 
    'p_finisdfishlurelegendary01x', 'p_finishdcrawdlegendary01x', 
    'p_lgoc_spinner_v4', 'p_lgoc_spinner_v6', 'mp001_p_mp_still02x'
);

-- Pas 2: Adaugare iteme critice care lipsesc sau au casing gresit
-- Folosim INSERT IGNORE pentru a nu da eroare daca exista deja, dar recomandam rularea dupa MASTER_IMPORT.sql
INSERT IGNORE INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `metadata`, `weight`, `desc`, `degradation`) VALUES
('sugarcube', 'Sugar Cube', 50, 1, 'item_standard', 1, 1, '{}', 0.1, 'Zahar cai', 0),
('wild_carrot', 'Wild Carrot', 20, 1, 'item_standard', 1, 1, '{}', 0.2, 'Morcov salbatic', 0),
('provision_jail_keys', 'Jail Keys', 1, 1, 'item_standard', 1, 1, '{}', 0.1, 'Chei inchisoare', 0),
('doctor_keys', 'Doctor Keys', 1, 1, 'item_standard', 1, 1, '{}', 0.1, 'Chei doctor', 0),
('water', 'Water', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Apa', 0),
('whisky', 'Whisky', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Whisky', 0),
('beer', 'Beer', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Bere', 0),
('wine', 'Wine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Vin', 0),
('moonshineapple', 'Apple Moonshine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Alcohol', 0),
('moonshinepeach', 'Peach Moonshine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Alcohol', 0),
('moonshinepear', 'Pear Moonshine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Alcohol', 0),
('moonshineplum', 'Plum Moonshine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Alcohol', 0),
('jagtlizenz', 'Hunting License', 1, 1, 'item_standard', 1, 1, '{}', 0.1, 'Licenta vanatoare', 0),
('ammoshotgunexplosive', 'Ammo Shotgun Explosive', 100, 1, 'item_standard', 1, 1, '{}', 0.1, 'Munitie', 0),
('blood_flower_seed', 'Blood Flower Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('wild_carrot_seed', 'Wild Carrot Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('american_ginseng_seed', 'Ginseng Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('english_mace_seed', 'English Mace Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('apple_seed', 'Apple Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('oleander_sage_seed', 'Oleander Sage Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('sugarcaneseed', 'Sugar Cane Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('crows_garlic_seed', 'Crows Garlic Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('choc_daisy_seed', 'Choc Daisy Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('milk_weed_seed', 'Milk Weed Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('yarrow_seed', 'Yarrow Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('creeking_thyme_seed', 'Thyme Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('black_currant_seed', 'Black Currant Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('wintergreen_berry_seed', 'Wintergreen Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('oregano_seed', 'Oregano Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('parasol_mushroom_seed', 'Parasol Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('teaseeds', 'Tea Seeds', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('alaskan_ginseng_seed', 'Alaskan Ginseng Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('black_berry_seed', 'Black Berry Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('wild_mint_seed', 'Wild Mint Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('red_sage_seed', 'Red Sage Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('red_raspberry_seed', 'Raspberry Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('prairie_poppy_seed', 'Poppy Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('indian_tobbaco_seed', 'Tobacco Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('creekplum_seed', 'Creekplum Seed', 100, 1, 'item_standard', 1, 1, '{}', 0.01, 'Seed', 0),
('secondchance', 'Character Token', 1, 0, 'item_standard', 1, 1, '{}', 0.0, 'Resetare', 0),
('p_baitbread01x', 'Bread Bait', 100, 1, 'item_standard', 1, 1, '{}', 0.05, 'Bait', 0),
('p_baitcorn01x', 'Corn Bait', 100, 1, 'item_standard', 1, 1, '{}', 0.05, 'Bait', 0),
('p_baitcheese01x', 'Cheese Bait', 100, 1, 'item_standard', 1, 1, '{}', 0.05, 'Bait', 0),
('p_baitworm01x', 'Worm Bait', 100, 1, 'item_standard', 1, 1, '{}', 0.05, 'Bait', 0),
('p_baitcricket01x', 'Cricket Bait', 100, 1, 'item_standard', 1, 1, '{}', 0.05, 'Bait', 0),
('p_finisdfishlure01x', 'Lure', 10, 1, 'item_standard', 1, 1, '{}', 0.1, 'Lure', 0),
('p_boxcar_barrel_09a', 'Boxcar Barrel', 1, 1, 'item_standard', 1, 1, '{}', 5.0, 'Barrel', 0),
('consumable_honey_manuka', 'Manuka Honey', 20, 1, 'item_standard', 1, 1, '{}', 0.3, 'Miere', 0),
('tropicalpunchmoonshine', 'Tropical Moonshine', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Bautura', 0),
('wildcidermoonshine', 'Wild Cider', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Bautura', 0),
('raspberryale', 'Raspberry Ale', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Bautura', 0),
('peyote', 'Peyote', 10, 1, 'item_standard', 1, 1, '{}', 0.1, 'Drog', 0),
('knotmeat', 'Knot Meat', 20, 1, 'item_standard', 1, 1, '{}', 0.3, 'Carne', 0),
('consumable_beefstew', 'Beef Stew', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Mancare', 0),
('cooked_game', 'Cooked Game', 20, 1, 'item_standard', 1, 1, '{}', 0.4, 'Mancare', 0),
('cooked_biggame', 'Cooked Big Game', 20, 1, 'item_standard', 1, 1, '{}', 0.5, 'Mancare', 0),
('cooked_bird', 'Cooked Bird', 20, 1, 'item_standard', 1, 1, '{}', 0.3, 'Mancare', 0),
('consumable_crumbcake', 'Crumb Cake', 20, 1, 'item_standard', 1, 1, '{}', 0.2, 'Prăjitură', 0),
('grape', 'Grape', 50, 1, 'item_standard', 1, 1, '{}', 0.1, 'Fruct', 0),
('caramel', 'Caramel', 50, 1, 'item_standard', 1, 1, '{}', 0.05, 'Dulce', 0),
('ciocolata', 'Ciocolata', 50, 1, 'item_standard', 1, 1, '{}', 0.1, 'Dulce', 0),
('consumable_jumari', 'Jumari', 20, 1, 'item_standard', 1, 1, '{}', 0.3, 'Mancare traditionala', 0),
('consumable_saltedcorn', 'Salted Corn', 50, 1, 'item_standard', 1, 1, '{}', 0.1, 'Mancare', 0),
('consumable_eggplantsalad', 'Zacusca', 20, 1, 'item_standard', 1, 1, '{}', 0.4, 'Zacusca / Salata vinete', 0),
('consumable_cabbagerolls', 'Sarmale', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Sarmale traditionale', 0),
('consumable_porkstew', 'Tocanita de porc', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_biggamestew', 'Tocanita vanat', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_tripe_soup', 'Ciorba de burta', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_chicken_stew', 'Tocanita pui', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_beef_cabbage', 'Varza cu vita', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_boiled_egg_polenta', 'Mamaliga cu ou', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare calda', 0),
('consumable_fish_veggie_brine', 'Saramura peste', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Mancare traditionala', 0),
('consumable_omelette_bacon', 'Omleta cu bacon', 10, 1, 'item_standard', 1, 1, '{}', 0.4, 'Mic dejun', 0),
('consumable_meat_pie', 'Placinta cu carne', 10, 1, 'item_standard', 1, 1, '{}', 0.4, 'Mancare', 0),
('consumable_fruit_jam', 'Gem de fructe', 20, 1, 'item_standard', 1, 1, '{}', 0.3, 'Dulceata', 0),
('consumable_cow_cheese', 'Branza de vaca', 20, 1, 'item_standard', 1, 1, '{}', 0.4, ' Lactate', 0),
('consumable_honey_jar', 'Borcan miere', 20, 1, 'item_standard', 1, 1, '{}', 0.5, 'Miere naturala', 0),
('consumable_fruit_pie', 'Placinta fructe', 10, 1, 'item_standard', 1, 1, '{}', 0.4, 'Desert', 0),
('consumable_papanas', 'Papanas', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Desert traditional', 0),
('consumable_fruit_tart', 'Tarta fructe', 10, 1, 'item_standard', 1, 1, '{}', 0.4, 'Desert', 0),
('consumable_fruit_cake', 'Cozonac / Tort', 10, 1, 'item_standard', 1, 1, '{}', 0.6, 'Desert', 0),
('consumable_peachcobbler', 'Peach Cobbler', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Desert', 0),
('consumable_jam_pancakes', 'Clatite cu gem', 10, 1, 'item_standard', 1, 1, '{}', 0.4, 'Desert', 0),
('bandagesteril', 'Bandaj Steril', 20, 1, 'item_standard', 1, 1, '{}', 0.1, 'Medical', 0),
('herbalremedy', 'Remediu Herbe', 20, 1, 'item_standard', 1, 1, '{}', 0.2, 'Medical', 0),
('antibiotics', 'Antibiotice', 20, 1, 'item_standard', 1, 1, '{}', 0.1, 'Medical', 0),
('pipe_smoker', 'Pipa', 1, 1, 'item_standard', 1, 1, '{}', 0.3, 'Pipa tutun', 0),
('peacepipe', 'Peace Pipe', 1, 1, 'item_standard', 1, 1, '{}', 0.3, 'Pipa pacii', 0),
('soborno', 'Alcohol Soborno', 10, 1, 'item_standard', 1, 1, '{}', 0.5, 'Bautura spirtoasa', 0),
('cigaret', 'Cigarette', 20, 1, 'item_standard', 1, 1, '{}', 0.1, 'Tigara', 0);
